### ISSUE TITLE
Why static render methods?

### ISSUE THREAD

**Issue by shoover** [Raynos/mercury#191]
Just curious why mercury component render methods are static since naively it would be convenient for a parent component to call foo.render() as an instance method. Is that mainly to enforce separation from the state object and discourage mutating local state?

Thanks very much for the excellent docs and examples. Mercury is an enlightening project.

**Comment by eightyeight** [comment]
You can definitely do that. I advocate separating render functions completely into their own files because

 1. Hot reloading is easier to do
 2. It makes it more difficult for the view to update model state in unexpected ways (the only sanctioned way is by binding channels to the DOM) There is always the possibility for local state in renderers, what you want is for the model to control access to itself via channels
 3. Ideologically, model and view should be separate. There are many ways one might want to render a boolean state; so instead of duplicating the state in several components (tickbox component, switch component), separate state and renderer (boolean state + tickbox renderer or switch renderer)

2 and 3 are just my opinion. Raynos does seem to lean more componentwards in some of the examples, for example how most render methods are attached to an object, not completely free.

**Comment by criloz** [comment]
@shoover  is not a requirement of the library just a way in which Raynos do the examples,  because he likes more functional programming,  in your I see that you want to use and OO paradigm, a option then is create local state in each component, at attach them to his parent component state,  and the parent state to its parent-parent state, and soon on till the root State (making you State tree in the process) when the class are loaded, using observ-struct, observ-array, or observ-varhash. if you are careful and understand the code that  is really small and easy to comprehend, you will archive the same using the OO paradigm.

this approximation is good  for me because In my case when I think about  the model of the app, I relate it more with the db data (users, tasks, messages, etc. very similar and what you should have in a db).  the ui for me can represent  that data in different ways, so the state of db-data like should not be tied to a UI component. and the Ui component should has its own state. (is just my approximation) 

I archive this in this way: ( Warning: this is pseudo code can contains  many errors)


``` javascript
    // Create global variable that you will use  ref the db models
    GLOBAL_VARIABLE = {};

    // load your model here, you can define all your model structure like  you do when use db- schemes    
    // and use observ-struct (prefer this), or be more be scheme less and use observ-varhash  
    // and a reference to the db model in the global variable

    GLOBAL_VARIABLE.model = mercury.varhash({});

    // load the ui classes tree
    var ui = new UI()

    // Create the app state
    var appState = mercury.struct("model": GLOBAL_VARIABLE.model, "ui": ui.state);

    mercury.app(document.body, appState, ui.render);


    // is important that you UI.render has the state as argument,  you just can ignore it after, because you 
    // are using the component state for render


    class UI{
         constructor():{
                state = {}
                //load your component 1
                this.c1 = Component1();
                state["c1"] = c1.state 
                // load your component n
                this.cn = Component_n();
                state["cn"] = cn.state 
               
               //the magic occurs here 
              this.sate = mercury.struct(state);
         }
        render(state):{
           //just ignore the state
            return mercury.h("div", {}, this.c1, ...., this.cn);
         }
    }
```
* For this has effect the child state should be Observ-values, Obsev-Arrays, Observ-Struct, or Observ-Varhash, or some similar object. 

* you can access to you db model from the component using the global variable.

* also I will recommend you use EventEmmiter or EventEmmiter2 or any similar thing for communication between components ( to  communicate events-things-stuff like Modal.onClose), just avoid modify  state outside of its  component.

Sorry for my broken English I hope that this example can help you.

**Comment by shoover** [comment]
Thank you, @eightyeight and @criloz, for the helpful explanations. I can see there is room for changing designs to suit the application but the examples seem to do it one particular way that ensures a functional perspective. I see this separation enforced in many Elm designs, as well.
